about/urls.py
from django.urls import path
from . import views

app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_post'),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]

posts/models.py
import textwrap

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """A group section model for grouping user posts.
    So far, the group is created by the administrator.
    """

    title = models.CharField(
        verbose_name='Название',
        max_length=200,
        help_text='ГранЪесловникЪ для группы дать',
    )
    slug = models.SlugField(
        verbose_name='Слаг',
        max_length=200,
        unique=True,
        blank=True,
        help_text='Задать руками иЛЪ оставить машинамЪ шансЪ',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Группы описания',
    )

    def __str__(self):
        return textwrap.shorten(self.title, 15)


class Post(models.Model):
    """Specified model by conditions.
    The main site model.
    """

    text = models.TextField(
        verbose_name='Тело поста',
        help_text='Наполнить пост',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        help_text='Выбор группы не обязателен, '
                  'но желателен',
    )

    def __str__(self):
        return textwrap.shorten(self.text, 15)


class Meta:
    ordering = ('-pub_date',)

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group',)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import PostForm
from posts.models import Group, Post, User


def index(request):
    latest = Post.objects.all()
    paginator = Paginator(latest, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page},
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'group.html',
        {'group': group, 'page': page}
    )


@login_required
def new_post(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('index')
    return render(request, 'new.html', {'form': form})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    if request.user != post.author:
        return redirect('post', username=username, post_id=post.id)
    form = PostForm(request.POST or None, instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post', username=username, post_id=post.id)
    return render(
        request,
        'new.html',
        {'form': form, 'post': post, 'is_edit': True})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'author': user, 'page': page}
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    context = {
        'author': post.author,
        'post': post,
    }
    return render(request, 'post.html', context)

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('signup')
    template_name = 'signup.html'

templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Об авторе
                </div>
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">
          <div class="card-text">
            <p>Текст страницы "Об авторе"</p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Технологии
                </div>
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">
          <div class="card-text">
            <p>Текст страницы "Технологии"</p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>
    {% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube
  </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
  {% include "includes/nav.html" %}
  <main>
    <div class="container">
      <h1>{% block header %}{% endblock %}</h1>
      {% block content %}
      {% endblock %}
    </div>
  </main>
  {% include "includes/footer.html" %}
</body>

</html>

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <p>
    {{ group.description }}
  </p>
  {% for post in page %}
    <h3>
      Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    <hr>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/includes/card_user.html
<div class="card">
  <div class="card-body">
    <div class="h2">
      {{ author.get_full_name }}
    </div>
    <div class="h3 text-muted">
      @{{ author.username }}
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="h6 text-muted">
        Подписчиков: XXX <br />
        Подписан: XXX
      </div>
    </li>
    <li class="list-group-item">
      <div class="h6 text-muted">
        Записей: {{ author.posts.count }}
      </div>
    </li>
  </ul>
</div>
</div>

templates/includes/footer.html
{% now "Y" as current_year %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    Социальная сеть
    <span style="color:red">Ya</span>tube © {{ current_year }}, все права защищены.
  </p>
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">«Об авторе»</a>
    <a href="{% url 'about:tech' %}">«Технологии»</a>
  </p>
</footer>

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <a href="{% url 'admin:index' %}" class="btn btn-outline-secondary">Admin Panel</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    Пользователь: {{ user.username }}.
    <a class="p-2 text-dark btn btn-outline-secondary" href="{% url 'new_post' %}">
      Новая запись
    </a>
    <a class="p-2 text-dark btn btn-outline-secondary" href="{% url 'password_change' %}">
      Изменить пароль
    </a>
    <a class="p-2 text-dark btn btn-danger" href="{% url 'logout' %}">
      Выйти
    </a>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'login' %}">
      Войти
    </a> |
    <a class="p-2 text-dark" href="{% url 'signup' %}">
      Регистрация
    </a>
    {% endif %}
  </nav>
</nav>

templates/includes/one_post.html
<div class="card mb-3 mt-1 shadow-sm">
  <div class="card-body">
    <p class="card-text">
      <a href="{% url 'profile' author %}">
        <strong class="d-block text-gray-dark">
          @{{ author.username }}
        </strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group ">
        <a class="btn btn-sm text-muted" href="/leo/37/" role="button">
          Добавить комментарий
        </a>
        <div class="btn-group ">
          {% if user == post.author %}
            <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author post.id %}" role="button">
              Редактировать
            </a>
          {% endif %}
        </div>
      </div>
      <small class="text-muted">
        {{ post.pub_date|date:"d M Y" }}
      </small>
    </div>
  </div>
</div>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">&laquo; Предыдущая</span>
      </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}
            <span class="sr-only">(текущая)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Следующая &raquo;</span>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% for post in page %}
    <h3>
      Автор:
        <a href="{% url 'profile' post.author.username %}" style="color:#000000; text-decoration:none">
          {{ post.author.get_full_name }},
        </a>
      Дата публикации:
        {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>
      <a href="{% url 'post' post.author post.id %}" style="color:#000000; text-decoration:none">
        {{ post.text|linebreaksbr }}
      </a>
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/new.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Создание поста
  {% endif %}
{% endblock %}
{% block header%}{% endblock %}
{% block content %}
  {% load user_filters %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактирование поста
            {% else %}
              Создание поста
            {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for error in form.errors.values %}
                <div class="alert alert-danger" role="alert">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

            <form method="post" action={% if is_edit %}"{% url 'post_edit' user.username post.pk %}"{% else %}"{% url 'new_post' %}"{% endif %}>
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                  <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required">
                        *
                      </span>
                    {% endif %}
                  </label>
                  <div class="col-md-6">
                    {{ field|addclass:"form-control" }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                </div>
              {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Добавить
                  {% else %}
                    Сохранить
                  {% endif %}
                </button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block title %}Post View{% endblock %}
{% block header %}Просмотр поста{% endblock %}
{% block content %}
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-3 mb-3 mt-1">
        {% include "includes/card_user.html" %}
        <div class="col-md-9">
          {% include "includes/one_post.html" %}
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-3 mb-3 mt-1">
        {% include "includes/card_user.html" %}
        <div class="col-md-9">
          {% include "includes/one_post.html" %}
          <p class="card-text">
            {%for post in page%}
              <a href="{% url 'profile' author %}">
                <strong class="d-block text-gray-dark">
                  @{{ author.username }}
                </strong>
              </a>
              <a href="{% url 'post' post.author post.id %}" style="color:#000000; text-decoration:none">
                {{ post.text|linebreaksbr }}
              </a>
              <hr>
            {%endfor%}
          </p>
          {% include "includes/paginator.html" %}
        </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block header%}Регистрация{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

              {% for error in form.errors.values %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %} 